### ISSUE TITLE
windows 10 运行 wtfpython 报错

### ISSUE THREAD

**Issue by CoreJK** [leisurelicht/wtfpython-cn#24]
电脑上安装的python 版本是：3.6.7
已经通过 pip 安装好了 wtfpython
但是运行时报错 "GBK" 编码错误
 `Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python3\Scripts\wtfpython.exe\__main__.py", line 9, in <module>
  File "c:\python3\lib\site-packages\wtf_python\main.py", line 31, in load_and_read
    render_doc()
  File "c:\python3\lib\site-packages\wtf_python\main.py", line 25, in render_doc
    content = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 284: illegal multibyte sequence`

**Comment by leisurelicht** [comment]
呃，这个编码问题真的比较尴尬，原作者打包的时候应该没考虑平台问题。我也只能推荐你不要在命令行下阅读。
